site_name: artwork
site_description: 'a framework for everything roblox'
docs_dir: docs/
repo_url: 'https://github.com/ratplier/artwork'
site_url: 'https://ratplier.github.io/artwork/'

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: artwork-dark
      toggle:
          icon: octicons/sun-24
          title: Switch to light theme
    - media: "(prefers-color-scheme: light)"
      scheme: artwork-light
      toggle:
          icon: octicons/moon-24
          title: Switch to dark theme

  custom_dir: docs/assets/overrides
  features:
    - navigation.tabs          # Use tabs for top-level navigation
    - navigation.sections      # Group pages into sections in the sidebar
    - navigation.instant       # Load pages instantly without full reloads
    - navigation.top           # Add a "Back to top" button
    - search.suggest           # Show search suggestions as you type
    - search.highlight         # Highlight search terms on the page
    - content.tabs.link        # Linkable content tabs
    - content.code.annotate    # Add annotations to code blocks
    - content.code.copy        # Add a "copy to clipboard" button to code blocks

extra_css:
  - docs/assets/theme.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ratplier
